apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-demo-app
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::283800772211:role/devops-demo-production-app-irsa-role
  labels:
    app: devops-demo
    environment: production
